### ISSUE TITLE
Oops! The server takes too much time to respond

### ISSUE THREAD

**Issue by mwt** [movim/movim#1026]
My server is mwt.me

When I try to login to mov.im I instantly get the error that the server takes too much time to respond. It happens regardless of whether the credentials are correct.

It takes much less time than a usual timeout.

This XMPP server is hosted through conversations.im

**Comment by edhelas** [comment]
Was a certificate issue

**Comment by mwt** [comment]
Some more information:

* This only happened over xmpps
* Gajim and conversations.im get a valid certificate over xmpps
* I fixed the issue by deleting my xmpps record (such that it presumably connected over xmpp)
* Replacing the certificate with a new one did not fix the issue over xmpps

I use conversations.im hosting and movim obtained the conversations.im certificate via xmpps (as opposed to my certificate). Is it possible that the correct hostname isn't being sent to the server when using xmpps?

As far as I know, the xmpp and xmpps certificates are the same.

**Comment by aereaux** [comment]
I'm getting what appears to be a similar issue with my server (jmad.org, using the mov.im instance).  I don't want to remove the xmpps records because I believe they come in useful in weird environments.

I see an error about `TLS handshake error: callback failed` in my prosody log that I think is related, although I'm not sure if this indicates an error on the movim side or on the prosody side.

`openssl s_client -connect server1.jmad.org:5223 -servername jmad.org` seems to work (`server1.jmad.org` is the target of my server's SRV record).

**Comment by edhelas** [comment]
Seems related to #974

**Comment by ghost** [comment]
I am having the same issue with my server.
