### ISSUE TITLE
image upload failed

### ISSUE THREAD

**Issue by ghost** [movim/movim#1052]
Hello,
when i was draw someting and click send button, add image/photos or someting for send to anyone or paste image url where i am typed text it showed an error "upload failed". how can i solve this error?

I am used ubunto live server in esxi 6.7.

**Comment by edhelas** [comment]
The issue is not on the Movim side but on your XMPP side. We provide some documentation on how to configure it properly to prevent such issues.

For ejabberd: https://github.com/movim/movim/wiki/Configure%20ejabberd#http-upload
For prosody: https://github.com/movim/movim/wiki/Configure%20prosody#http-upload

There's a lot of chances that it's a CORS issue.
