### ISSUE TITLE
Use of Unsalted session hash

### ISSUE THREAD

**Issue by FranciscoCunha97** [movim/movim#1147]
The session hash is weak because of the use of SHA-1 and lack of salt, meaning there is a way to use collisions
to hijack sessions.
In the movim/app/Session.php file, the session hash is created from the SHA-1 hash of the "username.password.host", this cookie structure leads to static hash values over a long period of time, unless the password or host is changed regularly. The consistent use of the hash leads to high levels of exposure.

The recommendations is a part of a privately disclosed report, with the id MOV-002.

**Comment by Joao-Felisberto** [comment]
Since I am unable to install and run movim locally, I cannot test a fix for this issue, so, I'll just compile some guidelines and pointers for further research. My apologies for not providing a solution.

According to this [SO reply](https://stackoverflow.com/a/1581919) (last updated in 2017 for PHP 5.5.0), it is recommended to use [password_hash](https://www.php.net/manual/en/function.password-hash.php) and [password_verify](https://www.php.net/manual/en/function.password-verify.php), **without providing a salt** (`password_hash` already provides it) and adding a pepper, perharps generated at instalation time or provided by the instance admin when installing via configuration.

This will most likely require more substantial backend changes in order to ensure backwards compatibility for salt and pepper storage. It is worth noting that when accepting pepper from user input, a default value should not be provided, since users will tend to leave it as is, compromising the security of the passwords.

**Comment by edhelas** [comment]
Actually it is still possible to play around with the strings, lets find a better way to do it.

**Comment by edhelas** [comment]
This will requires to have a proper JID validation, related to https://github.com/movim/movim/issues/492#issuecomment-789242336
