### ISSUE TITLE
Movim.eu, various XMPP account registration and login issues

### ISSUE THREAD

**Issue by HansLachman** [movim/movim#1360]
I encountered various issues when attempting to register and use an XMPP account, and documented them in a write-up of what actions I took and the results of those actions, see attached text file. I previously posted this file in the xmpp.org GitHub project ( https://github.com/xsf/xmpp.org/issues/1419 ), and since some of the issues involve Movim.eu, they suggested I post about it here (movim GitHub project), so I'm attaching the same write-up - see Chapters 4, 6, 7 for Movim-specific issues, and specifically Suggestions 4a, 6a, 6b, 7a (although it was suggested in the response from xmpp.org that 4a might be intentional on the part of Movim, but I think at least the other 3 issues may be actionable issues in the Movim project).
[xmpp-adv.txt](https://github.com/user-attachments/files/16904098/xmpp-adv.txt)

**Comment by edhelas** [comment]
You have to differentiate 3 things here:

1. Movim as a project, a self deployable solution that you can install on your server to allow XMPP accounts to connect on the XMPP network
2. movim.eu (and jappix.com) as a XMPP server, not linked directly with 1., it's just a service hosted by the Movim team to allow people to easily register but is __not__ linked to the project
3. mov.im __one__ of the many deployed instance of Movim on the network

Now the services:

- movim.eu which is the home page of the Movim project
- join.movim.eu which is a service that allow one person to discover the other Movim instances deployed

On join.movim.eu you have a subservice that allow someone to register and manage its @movim.eu (or @jappix.com) XMPP account, there https://join.movim.eu/account/login and it is explained you wanted to use this form to authenticate on a Movim instance, which is not the case:

> Since the above didn't work, I decided to login to my Movim account on the Movim site itself. Previously, when I registered my account there, entering an email address was optional, so I didn't enter one. Now, the result of trying to login was a message, "An authentication link was sent to your XMPP account, please open it to finish the
authentication". 

![image](https://github.com/user-attachments/assets/af986204-df01-4fda-ae8b-0227c832f217)

It is presented as a __service__ that allows you to configure your account, the title AND the info box below clearly explain that it is __NOT__ to authenticate and use your account. As explained above join.movim.eu is just a service we host to discover other Movim instances and also register/manage your movim.eu (and jappix.com) accounts. 

Why all those services and choices ? Because my (as a maintener) goal is to __not__ have all the users register on movim.eu and join using mov.im, I don't want to create another centralized service and I want people to deploy and pick the XMPP server they want and the Movim instance they want.

Yes it's way easier to have one centralized service or a service like Mastodon where one instance = one account. On XMPP you have the choice of where you create your account (the XMPP server) and where you use it (using the many XMPP clients and Movim instances). 

I hope that it's clearer and you understand that. Try to see if you can find nice ideas to improve those flows and ecosystem while respecting those choices of keeping things separated.

Also one side note, putting some ticket information in a long attached text is not easy to handle, especially when the information are mixed with many others. My goal here is not to read blog post and try to figure out what is the issue, if you need to improve things I recommend to directly explain shortly what they are and try to propose some way to fix it directly in the ticket.

Regards,

edhelas
