### ISSUE TITLE
Only use the user locale for translations

### ISSUE THREAD

**Issue by linkmauve** [movim/movim#294]
My Movim installation is setup as French, but my browser Accept-Language is set to priorise Japanese.  I currently have the UI in a mix of Japanese (for things like the left menu when I’m logged in), English for untranslated strings, and French (for the right part of the logged-in main page, or for the login page before clicking on my account).

As a user, I would expect it to be fully in Japanese, or at least just Japanese with English for still-untranslated strings, with no French anywhere.

**Comment by edhelas** [comment]
This is actually quite difficult because the session is launched by the backend of Movim and it doesn't have access to the web server requests. By default the user have the language set by the admin but can set his own language in the configuration, this value is saved on his XMPP account and is then synchronized wherever he logs-in.

Closing the ticket.

**Comment by Ppjet6** [comment]
As much as I would like to avoid this, why not ignore Accept-Language then? How did the japanese sentences even got there in the first place? (if I understand correctly)
