### ISSUE TITLE
UX : degraded mode

### ISSUE THREAD

**Issue by baptistem** [movim/movim#372]
My xmpp server (prosody) doesn't provide PEP.
Which means that I'm in a degraded mode for the pubsub things.

In order to understand this, I had to read the doc, find out that the recommended server for movim is ejabberd and that the pubsub config on ejabberd is way more specific than what prosody allows.
Knowing that, I had to search internet to find out what are the differences between ejabberd and prosody to finaly find the thing about the PEP.

Would it be possible, either to update the documentation (which I can do easily) or name the XEP that movim need in the "degraded warning" in the settings view ?

**Comment by edhelas** [comment]
I'm not planning to give more information than that in the setting view. An average will not be able to understand what a XEP is. However I'm asking him to contact the administrator of the XMPP server.

I'd like to know what you would like to change in the documentation regarding this issue.

**Comment by c-93** [comment]
Well I just installed movim on my own prosody and searched for days because of this message.
There even are no messages on the admin interface concerning the missing (wrong) pep.
Maybe someone could add a sample configuration for prosody. The relevant part of the prosodu_lua.config would be sufficient.
Simply enabling pep and pubsub does not lead to non-degraded-mode.
Anyone knows how to setup a fully-working Movim with Prosody (v0.10)?

**Comment by edhelas** [comment]
Closing this ticket. See the Wiki why Prosody is not recommended for Movim for now.
