### ISSUE TITLE
Automatic Feedreader - Atom to Pubsub 

### ISSUE THREAD

**Issue by mulles** [movim/movim#390]
The idea is to make the miraculous python Script: [Atomtopubsub](https://github.com/edhelas/atomtopubsub/)  available for normal user through the general Movim WebUI. 

Example:
I want to add the following Atomfeed: https://rss.golem.de/rss.php?feed=ATOM1.0 
Best would be that you enter golem.de and "movim" would fetch the possible Atom feeds available for this domain and check if they have been added already. Next you choose the right one, and bingo new content available for movim users. 

Pro: -The user would be responsible for added Atom Content. 
       -A lot of content available on movim. 
Contra: work, that I am unfortunately not able to do out of the box as I already struggle to get Atomtopubsub running.

Further: fully integrate in movim installation

@edhelas please add Enhancement label.

**Comment by edhelas** [comment]
I'm tagging this as a wontfix because it's not in the aims of the Movim project to provide such feature.
All the content published on Movim is published by real users. This tool is only here to help some specific users to publish automatically some articles on the network. I think that generalizing this tool will not be a good thing for the quality of the content available on Movim.
