### ISSUE TITLE
Change the licence from AGPL to…

### ISSUE THREAD

**Issue by edhelas** [movim/movim#43]
There is some comments on Hacker News https://news.ycombinator.com/item?id=10175684 that complains about the AGPL licence which is used by Movim for the whole sourcecode.
I'm interested to see what other licence(s) can be use :)

**Comment by Jookia** [comment]
Just dropping by, I'm not sure there's really a need to change based on complaints. A lot of them talk about using code in other projects which is generally not what happens with projects unless it's a library (which Movim isn't, it's a serivce), and a lot of them talk about popularity in the sense that you should sacrifice a strong copyleft to again adoption or developers. I'm not sure if licensing has ever stopped people from using a social network (look at people using nonfree services), so I guess it boils down to people wanted to make nonfree extensions to Movim. Allowing this throws away compatibility and federation not in a technical sense but in a political sense. If everyone uses a single service because it has features that can't be shared, what use is federation?

**Comment by Jookia** [comment]
(github doesn't allow editing comments with free software, sorry for double post)

The only other thing I can think of is that you'd need to allow a nonfree version of the software to be used in an iOS port given all applications on the app store are nonfree due to the terms of service, making them incompatible with free copyleft licenses.

**Comment by edhelas** [comment]
I'm keeping the AGPLv3 for the moment, and I don't have plans to port Movim to iOS for the moment ;) But I leave this bug open.

**Comment by marxistvegan** [comment]
consider dual licensing when you consider this

**Comment by Jookia** [comment]
What would dual licensing accomplish that a single license wouldn't?

**Comment by edhelas** [comment]
This issue was moved to movim/movim#15

**Comment by trosel** [comment]
(A)GPL means your code will never be used or touched by a company and any coder or project that might build a startup. 

You could change the license to any of the following if you don't have the above as a goal.

* MIT
* Zlib
* Apache2
* BSD

**Comment by dos1** [comment]
I know some companies (and even work for one) where (A)GPL is perceived as preferred (or even required) way to license things, so I wouldn't use such strong words like "will never be touched" :P

**Comment by trosel** [comment]
@dos1 I'm just repeating what I've heard to add some color to the convo. 

Interesting perspective, thanks!

**Comment by jcbrand** [comment]
For the project I'm working on, [Converse.js](https://conversejs.org/), I chose the Mozilla Public License v2 as a compromise between very permissive (e.g. MIT) and strong copyleft (e.g. AGPL) licensing.

MPL states that the actual project files need to stay open source, but if you create new functionality in your own files, then you can license them how you want.

This works for Converse because it has a plugin system, so you can extend its functionality in new files. So far I've integrated it into various proprietary 3rd party websites without any complaints about the license. 

I'm not sure how relevant this is for Movim, but it might be something to look into as well.

There is of course the question whether it's possible to relicense Movim without getting explicit approval from every single contributor to the project (I think not).
