### ISSUE TITLE
News feed not refreshing automatically

### ISSUE THREAD

**Issue by abergmot** [movim/movim#540]
on Movim 0.12.01, the news feed doesn't automatically show new (private) posts from contacts anymore. I have to manually click on each contact to get their new content, and then it updates the News section for each contact visited.

(Also I'm not running my own server, I login to the pod nl.movim.eu )

**Comment by edhelas** [comment]
This is maybe not related to Movim itself but the XMPP setup. What XMPP servers are you, and your contacts, using?

**Comment by Trim** [comment]
Hello,

On my pod I see the same issue with communities: I'm subscribed to the LinuxFr communities on news.movim.eu and I see nothing in the news feed up to some user of the pod visits same communities.

It seems Movim doesn't receive notifications from xmpp server and use only its cached data.
Could you give me some hints on what I can look to diagnose this assumption ?

I'm running Debian Stretch with ejabberd 17.08 from backports. Movim is regulary merged with master, but I see this issue at least since October 2017.

**Comment by abergmot** [comment]
@edhelas  oh yeah I forgot to mention that, we're all on @movim.eu

**Comment by edhelas** [comment]
I was not able to reproduce the issue for now. Do you still have it ?

**Comment by Trim** [comment]
Well, I've just tested with a newly created Community on pubusb.movim.eu and it worked well.

Maybe the issue comes only from the news.movim.eu community server ?

Actually, my pod cant display the "LinuxFRNews" community from news.movim.eu (there's the movim cloud loading animation) and it shows me only 0 subscribed people and 63 news published when I'm looking with my personal XMPP account on my Movim pod.

Well, the "php linker.php" process was running with 100% CPU while the loading animation was running. I've let the process to terminate.

I've also unsubscribed and subscribed back: now I see there's well 244 subscribed people and news from last week appeared. Maybe I had to unsubscribe / subscribe back to have the communities on news.movim.eu working ?

I'm waiting for news on LinuxFR.orgNews community and I'll tell you if that worked or if the bug is still here.

**Comment by Trim** [comment]
I've made another test: I use my movim.eu account to post news while my adorsaz.ch Movim service is stopped (but xmpp server is running). The result is that the adorsaz.ch Movim pod don't know about new posts until I view each community: 
https://mov.adorsaz.ch/?post/pubsub.movim.eu/public-test-pubsub/2a1d482b-c399-47da-8d28-778ba729820f

Does pubsub work only with online clients ?

**Comment by abergmot** [comment]
I still have the issue on the web version of movim, not showing recent posts from my contacts (on @movim.eu) in the news section. 
**It is working nicely on the Movim android app** though, my news feed gets the news from my friends.

**Edit**: the strange thing is that I have another adress on @movim.eu, with 2 contacts from @movim.eu also, and on that account the news section did show the recent new posts with pictures from one of my contact. The only difference is that it was the first few posts my news section received, before that it was empty (beside 3 or 4 of my own posts)...

**Comment by edhelas** [comment]
Ok, I'm lost, is the issue coming from the XMPP accounts, the pod or the browser here ?

**Comment by edhelas** [comment]
Closing the ticket as I'm not able to reproduce with a proper use case.
