### ISSUE TITLE
No module handling this query when I want to add a new (Jabber) contact on nl.movim.eu

### ISSUE THREAD

**Issue by Roelofpieter** [movim/movim#585]
Hi. When I try to add a (jabber) contact in Movim it says: "No module is handling this query" . When I use a jabber client (Dino in my case) I can add the person (and it also shows up in my contacts in Movim). It does happen on nl.movim.eu and it doesn't happen on de.movim.eu. On the nl.movim.eu . I notice that I do have a pull down menu on nl.movim.eu letting me choose between "Enter the jabber ID", SMS (Cheogram) and vk (VK4XMPP). This is unavailable on de.movim.eu

**Comment by edhelas** [comment]
@singpolyma this is caused by the PR you made, can you have a look :) ?

**Comment by singpolyma** [comment]
looking into it...

**Comment by singpolyma** [comment]
I expect the bug is here: https://github.com/movim/movim/blob/99a9d9b12eaa91b023a178f13cecbbfe120a36b1/app/widgets/Roster/Roster.php#L153  -- this may be getting all presence objects for a whole server instead of only for the current user/roster.  @edhelas how would I change that to filter for the current roster?

**Comment by edhelas** [comment]
Damn that code is bad, in the future I'll review a bit better the PR done on Movim.
This is loading ALL the presences from the DB, then, one by one, doing a request to load the Caps and then checking if it's a gateway. The whole thing needs to be refactored. I'll do it but seriously…
