### ISSUE TITLE
consider openstatus

### ISSUE THREAD

**Issue by maddanio** [movim/movim#634]
Hi,

I just want to throw the question in there if you have considered integrating with [OStatus](https://en.wikipedia.org/wiki/OStatus)? I am thinking a lot about more distributed approaches to social networking and blogging, and it seems to me the key issue is standards and interfaces.

Best

**Comment by maddanio** [comment]
Just read up on it more. OStatus does not allow private feeds. Bummer. Then I am wondering how you encode the following (as there seems to be no pubsub standard for that?):
- likes
- mentions
- comments
- repeats (aka retweet, reblogs, ...)

**Comment by ivucica** [comment]
First, while it is called OStatus, I don't think it's called OpenStatus.

Second, OStatus is not a single protocol. Sooner you realize that, easier it is to reason about it.

It's got WebFinger, Atom Feeds, ActivityStreams, Salmon, PubSubHubbub (now being standardized as WebSub).

Vague descriptions from a layman that tried to fiddle with implementing a messy implementation in Go:

- WebFinger to provide attributes for an email address ("Hi HTTPS host <domain part>, tell me about user <user part>"). It is used to provide the URL to the atom feed, the endpoint for pushing Salmon posts,  user's public key used for signing in other protocols, and more.
- Atom Feeds to publish an XML representation of a user's timeline, as well as of individual posts.
- ActivityStreams to create a concept of various 'actions' that an object can perform on another object. For example, a Person can Favorite a Post. ActivityStreams can be represented as XML or JSON. It's being standardized.
- Salmon is used to notify a user-specific endpoint that an activity notable to that user has taken place. User being notified does not need to follow the originatin user. For instance, someone has mentioned them, or someone has liked them.
- PubSubHubbub is used to register your interest in receiving updates about a particular Atom feed endpoint.

A 'follow' action can, for instance, be implemented like this:

- create an Atom post containing an ActivityStreams object
- notify the user being followed using Salmon, by signing the Atom post using originating user's private key and pushing it over HTTP to the Salmon endpoint
- store the Atom post in originating user's timeline (possibly publishing it)
  - if it's been published, notify subscribers by pushing to their PubSubHubbub endpoints ('hubs')
- subscribe to the target user's PubSubHubbub endpoint ('hub')

> OStatus does not allow private feeds

What do you mean by a "private feed" in OStatus?

It doesn't matter if OStatus explicitly supports making a timeline private -- you just don't publish your private feed as a public Atom feed, nor do you expose a PuSH endpoint.

Mastodon has some flow for authorizing subscribers individually -- I am not familiar with the details.

> Then I am wondering how you encode the following (as there seems to be no pubsub standard for that?)

These activities are, in OStatus, encoded as ActivityStreams objects. One representation of Activity Streams is XML. This XML is published in the Atom Feed.

Correctly implementing OStatus in Movim would be... interesting. I have a vague feeling that this belongs in an OStatus-aware microblogging XMPP component, which Movim would carefully interact with. 

However, Movim has adopted many roles and handles many things itself, so maybe it can be tweaked into understanding OStatus and writing foreign, OStatus-federated feeds to appropriate nodes in a server's pubsub component. For instance, there can be one node per XMPP user, [ACLed](https://xmpp.org/extensions/xep-0060.html#subscriber-retrieve-perms) to just that user, and Movim could accept OStatus requests and write into that node.

I do think that interactions with OStatus would be complicated enough that they justify /carefully/ writing a XEP in order to guarantee interop of the stored data beyond just Movim.

**Comment by maddanio** [comment]
so how are these things encoded in movim then? i.e. likes, comments, and such?

**Comment by edhelas** [comment]
Everything is Atom on top of Pubsub 
- https://tools.ietf.org/html/rfc4287
- https://xmpp.org/extensions/xep-0060.html
- https://xmpp.org/extensions/xep-0277.html

>  ![](http://university.it/image/2017/04/reece.JPG)
> You don't have to reinvent protocols like WebFinger, Atom Feeds, ActivityStreams, Salmon, PubSubHubbub when you're reusing existing standards

**Comment by maddanio** [comment]
that last link helped a lot. it would be nice if these things where somewhere in the wiki :)

**Comment by edhelas** [comment]
I prefer to keep the Wiki as small as possible as it is hard to maintain/keep clean/updated. Those XEPs are listed here https://github.com/movim/moxl#xmpp-support.

**Comment by maddanio** [comment]
need to learn php now to help you guys :)

**Comment by ivucica** [comment]
I recognize GitHub is not a place for extended discussions. Still... https://xkcd.com/386 applies.

> You don't have to reinvent protocols like WebFinger, Atom Feeds, ActivityStreams, Salmon, PubSubHubbub when you're reusing existing standards

I think you meant the opposite of what you ended up saying :)

- Atom feeds are... well... Atom
- WebFinger is an IETF standard https://tools.ietf.org/html/rfc7033
- ActivityStreams 2.0 are a W3C standard https://www.w3.org/TR/activitystreams-core/
- PubSubHubbub is an older revision of a W3C standard https://www.w3.org/TR/websub/

The only one where I concede is Salmon, which is not a standard. It is, however, just a way to sign a piece of XML (pretty much an Atom entry), so it can be pushed. http://www.salmon-protocol.org/

Movim can ignore WebFinger, PuSH and Salmon. That's more than fine given its goals.

However, it would not be the worst idea in the world to adopt the XML representation of ActivityStreams (which is pretty much a few tags in Atom) to represent 'actions' such as likes. That is not covered by any of the docs you quoted. You mentioned Likes are represented as emoji comments -- that's, I'd argue, a novel approach and https://xkcd.com/927/ applies :)

**Comment by edhelas** [comment]
I'll try to keep it short.

I made the choice in Movim to not use "Web" standards for the social network side as I think that it's not wise to limit social networks to the Web. The Web standards are a small part of Internet standards and I prefer to rely on protocols like XMPP which sits on real time TCP streams better than HTTP-request-based-but-we-can-have-kinda-real-time solution like those protocols above.

I'm not saying that those protocols are bad, I'm just saying that they offer solutions that are fundamentally different than what you can do with XMPP and are mostly limited to specific problems of "social" features. 

Movim is not only about social network, it's also about IM, the XEPs above are just a piece of what XMPP can offer and integrate quite well with the rest. 

Now try to take one of the projects that are implementing those web protocols (Diaspora, Mastodon…) and see how they can do proper IM (real time presences, history, editing messages, chatrooms, multiple clients real-time sync…) on top of their solution, Diaspora tried with no big success…

I choose to take a more large protocol base that can handle all those things, you have one account (your JID) that sit on one server (your XMPP server) that communicate with services (transports, pubsub, chatrooms…) and everything else are just dumb clients, like Movim, that are dealing with this network using a TCP/TLS stream with XML packages inside. Everything is synchronised between all the clients, in real-time.

**Comment by ivucica** [comment]
FWIW in my case you're (mostly) preaching to the choir...

> I made the choice in Movim to not use "Web" standards for the social network side as I think that it's not wise to limit social networks to the Web. The Web standards are a small part of Internet standards and I prefer to rely on protocols like XMPP which sits on real time TCP streams better than HTTP-request-based-but-we-can-have-kinda-real-time solution like those protocols above.

Supporting XMPP as a first-party does not preclude compatibility with OStatus protocols.

(I'm removing the rest of the rant for now :))

**Comment by Natureshadow** [comment]
OStatus can (and imho should) be implemented on top of pubsub, but it does not have to be in Movim. Everyone would benefit from a standalone implementation.

**Comment by maddanio** [comment]
That makes sense. Decoupling is always good imho. Would adopting the acticitystreams bits require cooperation of Movim though?

**Comment by duven87** [comment]
pity..it would  be so nice to can follow all my groups, channels and people from GNU Social in Movim.. :'(

**Comment by edhelas** [comment]
Everyone can say the same with [insert my currently beloved social network here] platform. 
I think that the discussion was clear, if you want [Web Social Platform X] supported in Movim, create a XMPP transport for it.
