### ISSUE TITLE
I haven't words to say

### ISSUE THREAD

**Issue by p0liper** [movim/movim#640]
[user@hosting public_html]$ php ./vendor/bin/phinx migrate
Phinx by CakePHP - https://phinx.org. 0.9.2

using config file ./phinx.php
PHP Parse error:  syntax error, unexpected '?' in /volume/3/public_html/vendor/illuminate/database/Eloquent/Model.php on line 593
****
You're so cute, you can't fix these bugs before put it to production?

**Comment by oappiah** [comment]
I can't reproduce this

What PHP version are you using?
On what OS/dist version?

**Comment by edhelas** [comment]
I don't have words to say as well. First this bug is in a dependency of the project, so you should report it here.

Secondly the faulty code is 

```
if ($this->isDirty() && ($options['touch'] ?? true))
```

The null coalesce operator is indeed available only from PHP 7.0 which is the required version to run Movim now https://github.com/movim/movim/wiki/Install-Movim#get-started

Thanks to tell me that I'm cute :3
