### ISSUE TITLE
openfire-4.2.3: "movim in degraded mode, no pubsub support"

### ISSUE THREAD

**Issue by lkraav** [movim/movim#657]
Hi. It's my first attempt at connecting these two. Everything seems to work fine, except Movim apparently is not able to find pubsub support, which AFAIK Openfire does have. Nothing obvious is visible in the debug logs.

1. Is Openfire a known fully compatible XMPP backend for Movim?
2. If yes, which XMPP stanza copy-paste would you need from the log to diagnose?

**Comment by edhelas** [comment]
Unfortunately I don't have time to investigate the support of Movim with Openfire.
On top of that Movim will simply not work with Openfire because if this issue https://issues.igniterealtime.org/projects/OF/issues/OF-1433. I'll ping again the team about that.

I'm leaving this ticket open for a while to see how it evolve.

**Comment by lkraav** [comment]
@edhelas looks like they just fixed the upstream issue, and are scheduling it for 4.3.0 release.

What can be the next step for movim?

**Comment by edhelas** [comment]
The ticket is still open on their side (reopened), as I'm not planning to track that longer in Movim I'm closing this ticket for now.
