### ISSUE TITLE
Please set a username and password for the admin panel

### ISSUE THREAD

**Issue by p0liper** [movim/movim#666]
Permanent message:
```Please set a username and password for the admin panel (https://{{service}}/?admin)```
But ealier I was enter this data.

For example:
```root@partial:/var/www/html# php daemon.php config --username={{username}} --password={{password}}

root@partial:/var/www/html# php daemon.php start --url=https://{{webservice}} --port=8080 -d

Please set a username and password for the admin panel (https://{{webservice}}/?admin)
To set those credentials run
php daemon.php config --username=USERNAME --password=PASSWORD
root@partial:/var/www/html#```

**Comment by edhelas** [comment]
Is the database correctly setup?

**Comment by shynderman** [comment]
Same error.
My chronology:
```
 composer install
 php vendor/bin/phinx migrate
php daemon.php config --username=admin --password={{password}}
php daemon start --url=https://{{service}} --port=8080 -d
```
Output:
```
Please set a username and password for the admin panel (https://{{service}}/?admin)
To set those credentials run
php daemon.php config --username=USERNAME --password=PASSWORD
```

**Comment by JKingweb** [comment]
Same problem here.  Same steps as @shynderman. Using commit 4773c29bc861adae4d9d61553dd17c9b6b117569 (the latest at this time), by the way.

**Comment by JKingweb** [comment]
Digging a bit in the code I've been able to ascertain that [ConfigCommand](https://github.com/movim/movim/blob/4773c29bc861adae4d9d61553dd17c9b6b117569/src/Movim/Console/ConfigCommand.php#L84) assumes `$configuration` will always be an instance of `Configuration`, but it is instead `null` for me. If I understand Eloquent's code correctly, Movim [is trying](https://github.com/movim/movim/blob/4773c29bc861adae4d9d61553dd17c9b6b117569/app/Configuration.php#L45) [to retrieve](https://github.com/illuminate/database/blob/5.2/Eloquent/Builder.php#L152) the first row of the configuration table, but since there is no row, it's getting `null` back---and of course therefore none of the supplied arguments are found in `$configuration->fillable`, so it does nothing (and therefore never fails on `$configuration->$key = $value;` like it otherwise would).

Presumably adding a row of data would allow it to function, but I've no idea what to add.

**Comment by edhelas** [comment]
@JKingweb thanks a lot for the investigation, it helped me to track easily the issue :)
