### ISSUE TITLE
Movim may have issues with DNS records not being done in a certain fashion, causing some breakage

### ISSUE THREAD

**Issue by realkinetix** [movim/movim#741]
I had set up movim on a server that had all the components together - ejabberd, nginx (or apache depending on the day of testing), php7.2-fpm (debian stable installation).  The XMPP setup had the main domain have it's A records pointing to another server, but XMPP SRV records pointing to this server with the ejabberd and movim installation.  

With this setup, movim had very strange behaviour which included the logout button not functioning at all (which left me with having to manually remove cookies & clearing browser cache to be able to 'log out'), and in investigating other issues, Timothée could see that there were issues with sessions as well.

After re-doing the host/DNS setup so that the XMPP server was no longer using the main domain (isurf.ca), but instead a subdomain (chat.isurf.ca) and having all the SRV and A records pointing to this server with the ejabberd & movim installation on it, these strange issues all cleared up.

It seems like there may be some peculiar requirements for hostname/DNS setup for Movim to work reliably, but it was not clear from logs that were found what it was tripping up on.

Opening this bug at Timothée's request.   Please let me know if I've left out specific details that could help.

**Comment by edhelas** [comment]
I just tested, deploying Movim on a root domain seems to work correctly.

**Comment by realkinetix** [comment]
What if the root domain's A records are pointing elsewhere, and only SRV records point to the XMPP service on that other host?

**Comment by crosser** [comment]
I had problem with ejabberd (without movim) behaving "strange" for xmpp domains with SRV records pointing to an address different from the A record of the domain.

It turned out that erlang DNS resolver that is used to resolve SRV has different behaviour from the system `gethostbyname()` resolver that is used to resolve A. Namely, erlang resolver fails with NXDOMAIN if your /etc/resolv.conf is empty, while system resolver defaults to nameserver at localhost:53.

@realkinetix, check if your trouble might stem from the same problem.

**Comment by realkinetix** [comment]
@crosser The system's /etc/resolv.conf has always been populated and functioning.

**Comment by edhelas** [comment]
Closing the ticket, I've made some changes recently on how the DNS are handled.
