### ISSUE TITLE
Help for my VPS

### ISSUE THREAD

**Issue by JossyMall** [movim/movim#783]
I have a VPS with full access. But reading the installation procedure...it's too technical for me. I do not understand much of all these composer....docker...dependencies of a thing. Is there a service you offer where you help people like me install this piece of amazing perfection on our server? by giving the VPS details please can my situation be helped???

**Comment by realkinetix** [comment]
I think it's interesting that this is posted as an issue, but I believe I could help.  Feel free to email me at adam_github_movim@isurf.ca

**Comment by edhelas** [comment]
@JossyMall you can publish your request in the content and not the title.

Furthermore, before asking someone to install Movim on your VPS you can try to join our support chatroom xmpp:movim@conference.movim.eu (please don't ask here how to join the chatroom, there is already plenty of tutorials online that explains how to do so) and ask your questions there.

**Comment by JossyMall** [comment]
i looked up the tutorial...it's quiet technical for me. I was hoping
someone might be generous enough to help me out??

**Comment by edhelas** [comment]
Setting up a server or a service like Movim is always a bit "technical" because you have to understand at least how the things are working together. Again, you are invited to join our support chatroom where we have people that can help you and explain what you need.

Allowing someone on your VPS server is a security risk. I'd prefer to only do that in rare cases where it's really needed (specific debug for example).

Furthermore, having such "on-site" support is something that Movim, as a free software project, is not providing by default, that's why we have packages and technical documentation to do so. Such support is something that I'm personally doing for companies in exchange of money.

**Comment by JossyMall** [comment]
can you please point me to a video tutorial? My server is centOS is there
any possible guidlines i can get from you (an experienced user) that might
be of great importance for me...? The desktop build uses qt 5. WHAT VARIANT
OF QT5 I mean.... qt5.x?

**Comment by Natureshadow** [comment]
>i looked up the tutorial...it's quiet technical for me. I was hoping>
>someone might be generous enough to help me out??

Certainly. Find a local Linux community and ask them to show you the basics.

If installing Movim is too "technical" for you, please do not operate a server on the public internet.
