### ISSUE TITLE
Can't accept incoming call in Firefox

### ISSUE THREAD

**Issue by ValdikSS** [movim/movim#957]
User 1: Firefox 84.0.2 at nl.movim.eu
User 2: Conversations 2.9.4 on Android 10

Can call from Movim to Conversations, but calls from Conversations to Movim are never established. Conversations show either "ringing" or "connecting" state. Tested with two different XMPP servers in Conversations.

In Chrome, calls in both directions work fine.

**Comment by edhelas** [comment]
This is a known issue indeed. I'll tag it as a bug and see what I can do with it.

**Comment by baraganx** [comment]
Movim -> conversations : OK

> In Chrome, calls in both directions work fine.
it no longer works from "Conversations" (2.9.5+fcr on Android 7.0) to "Movim", even with "Chromium" (87.0.4280.141-0.1).
Did anyone manage it?

**Comment by M-Stenzel** [comment]
It might be related:

1. I can make an audio call connection from conversations to conversations, no problems here
2. Connections from movim to conversations, and vice versa fail and remain at "...ringing" state (background turned into green) - AFTER the Conversations user ACCEPTS the call. Connections from movim to movim do not work either.
3. stun/turn part of ejabberd (version 21.01) does not show any errors (TURN allocation for both partners). N. B. I changed from google servers to own STUN/TURN server, however, problem does not disappear with Google servers
4. Web browser error console does not show any error, tested with several Unix and Windows browsers (firefox, iridium, edge)
5. /usr/bin/php daemon.php -vvv ... does not show any error
6. I tested with self hosted movim (pod.xy-space.de, version 0.19) and nl.movim.eu with the same result (no call established)

In the sources I found the "...ringing" string, I guess next state should be "...connecting", but this never appears.

How to proceed?

Martin
 
P. S. What I DO not understand - which servers are responsible for audio and video bridge (such e. g. jitsi)? This is not part of movim, otherwise, please correct me.

**Comment by edhelas** [comment]
I'm not experiencing any audio/video call issues anymore when calling Movim from Conversations. 
Closing this ticket.
