### ISSUE TITLE
OMEMO

### ISSUE THREAD

**Issue by omexlu** [movim/movim#979]
Hello,

The Webclient doesn't support OMEMO? I had try it in demo but the messages from others are all encrypted?

Thanks.

**Comment by Neustradamus** [comment]
It is the biggest missing feature!
-> XEP-0384: OMEMO 0.3.0 with 12-bytes IV to have compatibility with all XMPP clients.

**Comment by omexlu** [comment]
Sad, need that :)

**Comment by eyome** [comment]
Hello,

Please, search before asking: there is at least one ticket about it.
OMEMO should come on Movim, one day...

**Comment by omexlu** [comment]
One day.. Nice. 😅🙈

**Comment by eyome** [comment]
Yes, one day.
https://github.com/movim/movim/issues/63

**Comment by omexlu** [comment]
cart opened this issue on 20 Oct 2015

🤣🤣

**Comment by Quix0r** [comment]
The problem here is, that the key required do decrypt needs to be stored (best) on the client (=browser). If it is stored server-side, well ... we have a problem. :-) And I guess that applies to anything where a key (in clear-text) is required: OTR, OMEMO, OpenPGP, ...

Local storage on browser side is one solution, but once cleaned, you have create another key to share with your contacts again. This is as far as I understand it.

**Comment by edhelas** [comment]
Same as #63

**Comment by Neustradamus** [comment]
OMEMO has been added in Movim 0.20!

Announcements:
- Movim 0.20 announcement -> https://mov.im/?node/pubsub.movim.eu/Movim/dd90cd1c-4bcd-45a5-88a3-220fd4280b21
- Movim 0.20 announcement -> HN: https://news.ycombinator.com/item?id=30475406
- Movim 0.20 announcement -> Movim subreddit: https://www.reddit.com/r/movim/comments/t1p7nz/movim_020_has_been_released_with_omemo_endtoend/
- Movim 0.20 announcement -> XMPP subreddit: https://www.reddit.com/r/xmpp/comments/t1p7tc/movim_020_has_been_released_with_omemo_endtoend/
